import paramiko
import sys
import time

results = []

def sftp_exists(sftp, path):
    try:
        sftp.stat(path)
        return True
    except FileNotFoundError:
        return False
    

def ssh_conn():
    client = paramiko.SSHClient()
    client.load_system_host_keys()
    client.connect('192.168.8.136', username='user', password = '1')
    remote_directory = '/home/user/polaris_showcase'
    local_directory = 'd:\\showcase\\'
       
    sftp_client=client.open_sftp()

    # 1. Create remote directory
    if not sftp_exists(sftp_client, remote_directory):
        sftp_client.mkdir(remote_directory)

    # 2. Copy script to remote directory
    sftp_client.put(f'{local_directory}remote_script.py',
                    f'{remote_directory}/remote_script.py')

    # 3. Run remote script
    ssh_stdin, ssh_stdout, ssh_stderr = client.exec_command(
        f'python3 {remote_directory}/remote_script.py')
    time.sleep(0.1)

    # 4. Get a report generated by remote script
    sftp_client.get(f'{remote_directory}/report.json',f'{local_directory}report.json')
        
    sftp_client.close()
    client.close()


ssh_conn()
sys.exit()
